
###
GET http://localhost:3000/api/persons

###
GET http://localhost:3000/api/persons/1

###
GET http://localhost:3000/info

###
DELETE http://localhost:3000/api/persons/5

###
POST http://localhost:3000/api/persons
Content-Type: application/json

{
    "name": "Mati Figueroa",
    "number": "351-3123456"
}

###
GET http://localhost:3000/api/hello