
###
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/1

###
GET http://localhost:3001/info

###
DELETE http://localhost:3001/api/persons/5

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Mati Figueroa",
    "number": "351-3123456"
}

###
GET http://localhost:3001/api/hello